site_name: Moodrobe
theme:
  name: material
  language: fr
  #logo: images/logo.png
  favicon: images/favicon.ico

  palette:
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/weather-night
        name: Passer en mode nuit
    - scheme: slate
      primary: pink
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Passer en mode jour
  features:
    - content.code.copy
    - navigation.top
    - navigation.sections
    - navigation.tabs
    - search.highlight
    - search.suggest
    - toc.integrate
    - navigation.instant
    - header.autohide
    - navigation.footer
    - content.tabs.link
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.select

nav:
  - Accueil: index.md
  - Data:
    - Data: data_card.md
    - Embeddings: embedding_card.md
    - Model: model_card.md
    - Result: results_summary.md
  - Tutoriels:
    - Test: test.md
  - Références: references.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tonrepo
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/tonprofil

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          docstring_style: google